import type { DocumentAnalysis } from "./contracts";

// Final compliance report (Markdown). Every finding carries its evidence and
// provenance, and every repair its human decision, so the report explains
// why each conclusion was reached and who accepted each change.

const esc = (text: string) => text.replace(/\|/g, "\\|").replace(/\n/g, " ");

export function buildComplianceReport(doc: DocumentAnalysis, generatedAt = new Date()): string {
  const lines: string[] = [];
  const count = (status: string) => doc.findings.filter((f) => f.status === status).length;
  lines.push(`# Compliance review report — ${doc.name}`, "");
  lines.push(
    "> **Decision support, not certification.** Findings and proposed repairs are generated by StandardOS and must be reviewed by qualified personnel. " +
      "StandardOS does not certify products or establish legal compliance. Standards content in the corpus is paraphrased metadata that has not been verified against official BIS publications.",
    "",
  );
  lines.push("## Analysis record", "");
  lines.push(`| Field | Value |`, `| --- | --- |`);
  lines.push(`| Organisation | ${esc(doc.organization)} |`);
  lines.push(`| Source format | ${doc.type} |`);
  lines.push(`| Analysed at | ${doc.analyzedAt} |`);
  lines.push(`| Report generated | ${generatedAt.toISOString()} |`);
  lines.push(`| Pipeline version | ${doc.pipelineVersion ?? "—"} |`);
  lines.push(
    `| Standards corpus | ${doc.corpusVersion ?? "—"} (${doc.corpusSource ?? "unknown source"}) |`,
  );
  lines.push(`| Requirements extracted | ${doc.requirementCount} |`);
  lines.push(`| Standards identified | ${doc.standards} |`);
  lines.push(`| Readiness | ${doc.readiness}% — \`${doc.readinessFormula ?? "n/a"}\` |`, "");
  if (doc.warnings.length)
    lines.push("**Parser warnings:**", ...doc.warnings.map((w) => `- ${w}`), "");

  lines.push("## Summary", "");
  lines.push(
    `- Conflicting: ${count("conflicting")}`,
    `- Outdated references: ${count("outdated")}`,
    `- Missing / insufficient: ${count("missing")}`,
    `- Certification: ${count("certification")}`,
    `- Verified: ${count("verified")}`,
  );
  lines.push(
    `- Findings dismissed by reviewer: ${doc.findings.filter((f) => f.reviewStatus === "dismissed").length}`,
    "",
  );

  lines.push("## Findings", "");
  doc.findings.forEach((f, i) => {
    lines.push(`### ${i + 1}. ${f.title}`, "");
    lines.push(
      `**Status:** ${f.status} · **Severity:** ${f.severity} · **Review:** ${f.reviewStatus ?? "open"}${f.reviewNote ? ` — “${f.reviewNote}”` : ""}`,
      "",
    );
    lines.push(
      `- **Requirement:** ${f.requirement}`,
      `- **Standard:** ${f.standard}`,
      `- **Reason:** ${f.reason}`,
      `- **Recommended action:** ${f.action}`,
    );
    if (f.evidence?.length) {
      lines.push("- **Evidence:**");
      for (const e of f.evidence)
        lines.push(`  - _${e.kind.replace(/_/g, " ")}_ — ${e.label}: ${e.excerpt}`);
    }
    if (f.provenance)
      lines.push(
        `- **Provenance:** ${f.provenance.component}@${f.provenance.componentVersion} · ${f.provenance.method}${f.provenance.model ? ` (${f.provenance.model})` : ""} · confidence ${f.provenance.confidence}`,
      );
    lines.push("");
  });

  lines.push("## Proposed specification repairs", "");
  if (!doc.repairs.length) lines.push("No repairs were proposed.", "");
  doc.repairs.forEach((r, i) => {
    lines.push(`### Repair ${i + 1} — ${r.status ?? "pending"}`, "");
    lines.push(`- **Original:** ${r.original}`, `- **Proposed:** ${r.recommended}`);
    if (r.status === "edited" || r.status === "accepted")
      lines.push(`- **Adopted text:** ${r.finalText ?? r.recommended}`);
    lines.push(`- **Evidence:** ${r.evidence}`, `- **Reason:** ${r.reason}`);
    if (r.provenance)
      lines.push(
        `- **Provenance:** ${r.provenance.component}@${r.provenance.componentVersion} · ${r.provenance.method}${r.provenance.model ? ` (${r.provenance.model})` : ""}`,
      );
    lines.push("");
  });

  lines.push(
    "## Requirement mapping",
    "",
    "| # | Requirement | Standard | Clause | Basis | Confidence |",
    "| --- | --- | --- | --- | --- | --- |",
  );
  for (const r of doc.requirements) {
    lines.push(
      `| ${r.id} | ${esc(r.text)} | ${esc(r.standard)} | ${esc(r.clause)} | ${r.basis ?? "—"} | ${r.confidence !== undefined ? r.confidence.toFixed(2) : "—"} |`,
    );
  }
  lines.push("");
  return lines.join("\n");
}
