import { createFileRoute,Link } from "@tanstack/react-router";
import { ArrowRight,GitBranch,ScanSearch,ShieldCheck,Split } from "lucide-react";
import { motion } from "motion/react";
import { PublicHeader } from "@/components/layout/public-header";
import { Button } from "@/components/ui/button";
export const Route=createFileRoute("/features")({head:()=>({meta:[{title:"Features — STANDARDOS"},{name:"description",content:"Specification intelligence, standards mapping, compliance auditing, and change-impact monitoring."},{property:"og:title",content:"Features — STANDARDOS"},{property:"og:description",content:"Designed around relationships, not keyword matches."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Features});
const fade={initial:{opacity:0,y:18},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.2},transition:{duration:.55}};
const capabilities=[{icon:ScanSearch,title:"Specification intelligence",text:"Extracts technical obligations, product categories, tolerances, and verification criteria from any procurement document."},{icon:GitBranch,title:"Standards dependency graph",text:"Traces every requirement through standards, normative references, tests, and certifications."},{icon:ShieldCheck,title:"Compliance auditing",text:"Surfaces missing, conflicting, obsolete, and unsupported clauses with the evidence behind each finding."},{icon:Split,title:"Change-impact monitoring",text:"Connects amendments to every live procurement document they may affect, before it becomes a problem."}];
function Features(){return <div><PublicHeader/><main className="page-wrap pb-24 pt-32"><motion.div {...fade}><p className="eyebrow">Core capabilities</p><h1 className="page-title mt-4 max-w-3xl text-5xl sm:text-6xl">Designed around relationships, not keyword matches.</h1></motion.div><div className="mt-16 grid gap-6 md:grid-cols-2">{capabilities.map(({icon:Icon,title,text},i)=><motion.article {...fade} transition={{duration:.45,delay:i*.06}} key={title} className="step-card glass-panel group rounded-xl p-7"><Icon className="size-6 text-accent-foreground transition-transform duration-300 group-hover:translate-x-1"/><h2 className="mt-5 text-xl font-bold text-primary">{title}</h2><p className="mt-3 max-w-lg leading-7 text-muted-foreground">{text}</p></motion.article>)}</div><motion.div {...fade} className="mt-16 overflow-hidden rounded-2xl bg-primary p-8 text-primary-foreground sm:p-10"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="eyebrow text-accent">Example analysis</p><h2 className="mt-3 font-display text-3xl leading-tight sm:text-4xl">A conflict a reviewer can act on.</h2><p className="mt-5 leading-7 text-primary-foreground/70">Not generic AI commentary—an exact requirement, governing reference, reason, severity, and recommended correction.</p></div><div className="rounded-2xl border border-primary-foreground/15 bg-primary-foreground/5 p-6 backdrop-blur-xl transition-all duration-300 hover:-translate-y-1 hover:bg-primary-foreground/10 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.12em] text-accent">Potential conflict detected</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><div><p className="text-xs text-primary-foreground/55">Tender requirement</p><p className="mt-2 font-semibold">Operating temperature: 120°C</p></div><div><p className="text-xs text-primary-foreground/55">Referenced condition</p><p className="mt-2 font-semibold">Normal ambient: 40°C</p></div></div><p className="mt-6 border-t border-primary-foreground/15 pt-5 text-sm leading-6 text-primary-foreground/70">IS/IEC 61439-1:2020 · Clause 7.1 · Special service verification required</p></div></div></motion.div><motion.div {...fade} className="mt-16 border-t border-border pt-10"><Button asChild size="lg"><Link to="/analyze">Analyze a Specification <ArrowRight/></Link></Button></motion.div></main></div>}
