import { createFileRoute,Link } from "@tanstack/react-router";
import { ArrowRight,FileCheck2,GitBranch,ScanSearch,ShieldCheck,Upload } from "lucide-react";
import { motion } from "motion/react";
import { PublicHeader } from "@/components/layout/public-header";
import { Button } from "@/components/ui/button";
export const Route=createFileRoute("/how-it-works")({head:()=>({meta:[{title:"How It Works — STANDARDOS"},{name:"description",content:"How STANDARDOS turns a specification into a compliance decision, from upload to corrected language."},{property:"og:title",content:"How It Works — STANDARDOS"},{property:"og:description",content:"One continuous evidence trail from source document to compliance decision."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:HowItWorks});
const fade={initial:{opacity:0,y:18},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.2},transition:{duration:.55}};
const steps=[{n:"01",title:"Upload",icon:Upload,text:"Bring a specification or tender as a PDF, DOCX, or pasted text. Nothing needs to be pre-formatted or tagged."},{n:"02",title:"Extract",icon:ScanSearch,text:"STANDARDOS reads the document for technical obligations, tolerances, product categories, and verification criteria."},{n:"03",title:"Map",icon:GitBranch,text:"Each requirement is traced to the Indian Standards, referenced clauses, tests, and certifications that govern it."},{n:"04",title:"Audit",icon:ShieldCheck,text:"Missing, conflicting, obsolete, and unsupported clauses are surfaced with the evidence behind each finding."},{n:"05",title:"Repair",icon:FileCheck2,text:"Corrected language is generated for every flagged clause, ready for a reviewer to accept or amend."}];
function HowItWorks(){return <div><PublicHeader/><main className="page-wrap pb-24 pt-32"><motion.div {...fade}><p className="eyebrow">How STANDARDOS works</p><h1 className="page-title mt-4 max-w-3xl text-5xl sm:text-6xl">One continuous evidence trail from source document to compliance decision.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">Every step keeps the original clause in view, so a reviewer can trace any recommendation back to its source.</p></motion.div><div className="relative mt-16 grid gap-5 md:grid-cols-5">{steps.map(({n,title,text,icon:Icon},index)=><motion.div {...fade} transition={{duration:.45,delay:index*.08}} key={title} className="step-card glass-panel rounded-xl p-6"><span className="grid size-10 place-items-center rounded-full bg-accent/50 text-accent-foreground"><Icon className="size-5"/></span><span className="mt-5 block text-xs font-extrabold tracking-[.1em] text-accent-foreground">{n}</span><h2 className="mt-2 text-lg font-bold text-primary">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p>{index<4&&<ArrowRight className="absolute -right-[11px] top-1/2 z-10 hidden size-4 -translate-y-1/2 text-accent-foreground md:block"/>}</motion.div>)}</div><motion.div {...fade} className="mt-16 border-t border-border pt-10"><Button asChild size="lg"><Link to="/analyze">Analyze a Specification <ArrowRight/></Link></Button></motion.div></main></div>}
