import { createFileRoute,Link } from "@tanstack/react-router";
import { ArrowRight,Check } from "lucide-react";
import { motion } from "motion/react";
import { PublicHeader } from "@/components/layout/public-header";
import { Brand } from "@/components/brand";
import { Button } from "@/components/ui/button";
export const Route=createFileRoute("/")({head:()=>({meta:[{title:"STANDARDOS — From Specifications to Certainty"},{name:"description",content:"Analyze procurement specifications, map Indian Standards, detect compliance gaps, and generate evidence-backed corrections."},{property:"og:title",content:"STANDARDOS — From Specifications to Certainty"},{property:"og:description",content:"Indian Standards intelligence for procurement and compliance teams."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Landing});
const fade={initial:{opacity:0,y:18},animate:{opacity:1,y:0},transition:{duration:.6}};
function Landing(){return <div id="home"><PublicHeader/><main><section className="relative flex min-h-screen items-center overflow-hidden pb-16 pt-32"><motion.img src="/hero-visual.webp" alt="" className="absolute inset-0 -z-20 h-full w-full object-cover" initial={{opacity:0,scale:1.04}} animate={{opacity:1,scale:1}} transition={{duration:1,ease:"easeOut"}}/><div className="absolute inset-0 -z-10 bg-gradient-to-r from-background/55 via-background/25 to-transparent"/><div className="site-container"><motion.div {...fade} className="max-w-2xl"><p className="eyebrow">Procurement intelligence · Indian Standards</p><h1 className="page-title mt-5 text-5xl sm:text-6xl lg:text-7xl">From Specifications to Certainty.</h1><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/analyze">Analyze a Specification <ArrowRight/></Link></Button><Button asChild size="lg" variant="outline"><Link to="/how-it-works">See How It Works</Link></Button></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-sm text-muted-foreground">{["Clause-level evidence","Conflict detection","Change-aware"].map((item)=><span key={item} className="flex items-center gap-2"><Check className="size-4 text-accent-foreground"/>{item}</span>)}</div></motion.div></div></section></main><footer className="border-t border-border py-10"><div className="site-container flex flex-col justify-between gap-6 sm:flex-row sm:items-center"><Brand/><p className="text-xs text-muted-foreground">Evidence-led procurement. Built for a stronger India.</p></div></footer></div>}
