import { createFileRoute,Link } from "@tanstack/react-router";
import { ArrowRight,Building2,ClipboardCheck,Factory,Landmark } from "lucide-react";
import { motion } from "motion/react";
import { PublicHeader } from "@/components/layout/public-header";
import { Button } from "@/components/ui/button";
export const Route=createFileRoute("/use-cases")({head:()=>({meta:[{title:"Use Cases — STANDARDOS"},{name:"description",content:"Built for procurement officers, manufacturers, compliance teams, and technical evaluators."},{property:"og:title",content:"Use Cases — STANDARDOS"},{property:"og:description",content:"Move faster without losing the evidence."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:UseCases});
const fade={initial:{opacity:0,y:18},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.2},transition:{duration:.55}};
const audiences=[{icon:Landmark,title:"Procurement officers",text:"Verify a tender specification against applicable Indian Standards before it goes out for bid, and catch conflicting clauses early."},{icon:Factory,title:"Manufacturers",text:"Confirm a product specification meets the standards a buyer will check against, with the clause-level evidence to prove it."},{icon:ClipboardCheck,title:"Compliance teams",text:"Audit specifications at scale and track which amendments affect which live documents, without re-reading every file by hand."},{icon:Building2,title:"Technical evaluators",text:"Move through bid evaluation with a documented, defensible trail from requirement to standard to recommendation."}];
function UseCases(){return <div><PublicHeader/><main className="page-wrap pb-24 pt-32"><motion.div {...fade}><p className="eyebrow">Built for consequential procurement</p><h1 className="page-title mt-4 max-w-3xl text-5xl sm:text-6xl">Move faster without losing the evidence.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">For teams working across infrastructure, utilities, manufacturing, and public works, where a missed clause has consequences.</p></motion.div><div className="mt-16 border-t border-border">{audiences.map(({icon:Icon,title,text},i)=><motion.div {...fade} transition={{duration:.4,delay:i*.06}} key={title} className="grid gap-4 border-b border-border py-8 sm:grid-cols-[auto_1fr] sm:items-start sm:gap-8"><Icon className="size-6 text-accent-foreground"/><div><h2 className="text-xl font-bold text-primary">{title}</h2><p className="mt-2 max-w-2xl leading-7 text-muted-foreground">{text}</p></div></motion.div>)}</div><motion.div {...fade} className="mt-16"><Button asChild size="lg"><Link to="/signup">Build your workspace <ArrowRight/></Link></Button></motion.div></main></div>}
