"""Third, independent wording of every clause, for the open ``dev2`` split.

Why: the rules were developed on variant 0 (the ``dev`` wording) and the blind
``test`` split uses variants 1+. Error analysis on ``test`` would leak it, so
``dev2`` gives an *open* split with wording no rule was written against. These
paraphrases were written from variant 0 only, without reference to the test
variants, and keep every value token, unit and citation (so the gold labels of
the template still hold). Unit spellings are a third pool too, disjoint from the
dev pool and from the test-only extras.
"""

from __future__ import annotations

FORMS_DEV2: dict[str, list[str]] = {
    "V": ["{n} V AC", "{n}-volt"],
    "kV": ["{n}-kV", "{n} kV AC"],
    "A": ["{n} Amperes", "{n} ampere"],
    "kA": ["{n} kA rms", "{n} kA (rms)"],
    "degC": ["{n} ℃", "{n}° C"],
    "mm2": ["{n} sq. mm", "{n} mm2", "{n} Sq mm"],
    "kW": ["{n} kilowatt", "{n} k.W."],
    "Hz": ["{n} Hertz", "{n} cycles per second"],
    "m3h": ["{n} m3/hour", "{n} cu.m/hr", "{n} m^3/h"],
    "mgl": ["{n} mg per litre", "{n} milligram per litre"],
    "ohm": ["{n} Ohms", "{n} ohm."],
    "mm": ["{n} millimetre", "{n} m.m."],
    "m": ["{n} metre", "{n} mtr"],
    "pct": ["{n} pct", "{n}% (percent)"],
    "kVA": ["{n} kva", "{n} kilo-volt-ampere"],
    "rpm": ["{n} rev/min", "{n} rpm."],
    "NTU": ["{n} NTU."],
    "dBA": ["{n} dB (A)", "{n} decibels (A)"],
    "kgm3": ["{n} kg per cubic metre", "{n} kg/cu.m"],
    "days": ["{n} calendar days"],
}

DEV2: dict[str, str] = {
    "docs.drawings": "Detailed shop drawings are to be submitted by the contractor for approval not later than {{21|days}} after the award of work.",
    "docs.manuals": "On completion the contractor shall hand over three copies of the O&M manuals.",
    "docs.warranty": "The contractor shall guarantee the whole installation for 12 months after handing over against faulty design, materials and workmanship.",
    "docs.inspection": "Before despatch, the Engineer-in-charge will inspect the equipment at the maker's works.",
    "docs.training": "Operation and routine maintenance training shall be given by the contractor to the Department's operators.",
    "vague.suitable_size": "Distribution boards shall be of suitable dimensions for the equipment housed.",
    "vague.reputed": "Equipment offered shall be of reputed manufacture and sturdy design.",
    "panel.ambient": "Equipment is to be rated for a maximum ambient temperature of {{40|degC}}.",
    "panel.humidity": "The relative humidity at site can go up to {{95|pct}}.",
    "panel.altitude": "The site is located at less than {{1000|m}} above MSL.",
    "panel.std": "The main LT switchboard shall comply with IS/IEC 61439-1:2020 and IS/IEC 61439-2:2020.",
    "panel.construction": "The switchboard shall be of floor standing cubicle construction using CRCA sheet steel {{2|mm}} thick.",
    "panel.voltage": "The switchboard shall have a rated operational voltage of {{415|V}}, 3 phase 4 wire, {{50|Hz}}.",
    "panel.busbar": "The main busbar shall be electrolytic grade aluminium with a continuous rating of {{1600|A}}.",
    "panel.sc": "The short time withstand current of the busbars shall be {{50|kA}} for one second.",
    "panel.ip": "The panel enclosure is to have a degree of protection of IP54.",
    "panel.form": "Internal separation of the switchboard shall be to Form 3b.",
    "panel.acb": "Each incomer shall be a {{1600|A}}, four pole, motorised air circuit breaker complying with IS/IEC 60947-2:2003.",
    "panel.mccb": "Outgoing feeders shall be controlled by MCCBs having an ultimate breaking capacity of {{36|kA}}.",
    "panel.metering": "Each incomer shall be provided with a class 0.5 accuracy multifunction meter.",
    "panel.gtp.voltage": "Rated operational voltage: {{415|V}}",
    "panel.gtp.current": "Main busbar rated current: {{1600|A}}",
    "panel.gtp.sc": "Rated short-time withstand current: {{50|kA}} for 1 s",
    "panel.gtp.ip": "Enclosure degree of protection: IP54",
    "panel.routine": "Each assembly shall undergo routine verification as laid down in IS/IEC 61439-1.",
    "panel.typetest": "The bidder shall furnish type test certificates of the offered panel design issued by a NABL accredited laboratory.",
    "panel.ambient.hot": "Equipment is to be rated for a maximum ambient temperature of {{50|degC}}.",
    "panel.altitude.high": "The site is located {{2600|m}} above MSL.",
    "panel.std.old": "The main LT switchboard shall comply with IS 8623 (Part 1):1993.",
    "panel.std.part2only": "The main LT switchboard shall comply with IS/IEC 61439-2:2020.",
    "panel.sc.vague": "Busbars shall be capable of withstanding the system fault level.",
    "wiring.code": "All wiring work shall comply with IS 732:2019.",
    "wiring.system": "The earthing arrangement of the supply system is TN-S.",
    "wiring.conduit": "All wiring shall run concealed in rigid PVC conduit having {{1.5|mm}} wall thickness.",
    "wiring.wires": "Wires are to be single core, stranded copper conductor, FR PVC insulated, 450/750 V grade to IS 694:2010.",
    "wiring.sizes": "Copper conductors of {{1.5|mm2}} shall be used for lighting circuits and {{4|mm2}} for power circuits.",
    "wiring.wiretest": "Testing of wires shall be done as per IS 10810.",
    "wiring.mcb": "MCBs shall comply with IS/IEC 60898-1 and have a rated short-circuit capacity of {{10|kA}}.",
    "wiring.mcbrating": "MCBs from {{6|A}} up to {{32|A}} shall be provided as per the single line diagram.",
    "wiring.rccb": "All socket outlet circuits shall be protected by 30 mA RCCBs complying with IS 12640 (Part 1).",
    "wiring.earthcode": "The earthing installation shall comply with IS 3043:2018.",
    "wiring.electrodes": "The main distribution board shall be earthed through two pipe earth electrodes.",
    "wiring.earthres": "Resistance of the earthing system shall be not more than {{1|ohm}}.",
    "wiring.completiontest": "After completion, the insulation resistance and earth continuity of the installation shall be tested as per IS 732.",
    "wiring.isi": "All wires, MCBs and RCCBs supplied shall carry the ISI mark.",
    "wiring.code.old": "All wiring work shall comply with IS 732:1989.",
    "wiring.wires.1100": "Wires are to be single core, stranded copper conductor, FR PVC insulated, 1100 V grade to IS 694:2010.",
    "wiring.mcb.old": "MCBs shall comply with IS 8828 and have a rated short-circuit capacity of {{10|kA}}.",
    "wiring.earthcode.old": "The earthing installation shall comply with IS 3043:1987.",
    "wiring.completiontest.vague": "The complete installation shall be tested after completion.",
    "cable.xlpe": "LT power cables shall be aluminium conductor, XLPE insulated, armoured, PVC sheathed, 1.1 kV grade, complying with IS 7098 (Part 1):1988.",
    "cable.size": "The size of the main feeder cable shall be 3.5 core {{300|mm2}}.",
    "cable.temp": "Maximum continuous conductor temperature of the cables shall be {{90|degC}}.",
    "cable.control": "Copper conductor control cables of {{2.5|mm2}}, PVC insulated, 1.1 kV grade shall comply with IS 1554 (Part 1).",
    "cable.conductor": "Class 2 stranded conductors complying with IS 8130 shall be used.",
    "cable.test": "Testing of the cables shall be done as per IS 10810.",
    "cable.laying": "Cables shall be run in RCC trenches or on perforated trays as per drawings.",
    "cable.glands": "Double compression glands and crimped lugs shall be used for all cable terminations.",
    "cable.drums": "The maker's name, size, voltage grade and year of manufacture shall be marked on every drum.",
    "cable.certs": "Each consignment of cables shall be accompanied by routine test certificates.",
    "cable.xlpe.11kv": "LT power cables shall be aluminium conductor, XLPE insulated, armoured, PVC sheathed, 11 kV grade, complying with IS 7098 (Part 1):1988.",
    "motor.std": "Squirrel cage induction motors complying with IS 325:1996 shall be supplied.",
    "motor.power": "Motor rated output shall be {{37|kW}}.",
    "motor.supply": "Motors are to operate on {{415|V}} ± {{10|pct}}, {{50|Hz}} ± {{5|pct}}, three phase supply.",
    "motor.ie": "Motors shall meet efficiency class IE3 of IS 12615:2018.",
    "motor.ip": "The motor enclosure shall have IP55 degree of protection.",
    "motor.insulation": "Insulation shall be class F, with temperature rise restricted to class B, for continuous S1 duty.",
    "motor.speed": "The motor synchronous speed shall be {{1500|rpm}}.",
    "motor.test": "Each motor shall be subjected to routine tests as per IS 4029.",
    "motor.cert": "All motors shall carry the ISI mark.",
    "motor.supply.15": "Motors are to operate on {{415|V}} ± {{15|pct}}, {{50|Hz}} ± {{5|pct}}, three phase supply.",
    "motor.ie.vague": "Motors shall be of high efficiency type.",
    "pump.std": "The pumps shall comply with IS 1520:1980.",
    "pump.duty": "Duty point of each pump shall be {{250|m3h}} at {{45|m}} total head.",
    "pump.eff": "Pump efficiency at the duty point shall be {{78|pct}} minimum.",
    "pump.materials": "The pump casing shall be cast iron and the impeller bronze.",
    "pump.noise": "The pumpset noise level measured {{1|m}} away shall be limited to {{85|dBA}}.",
    "pump.test": "Works testing of the pumps shall be done as per IS 9137.",
    "pump.isi": "All pumps shall carry the ISI mark.",
    "pump.gtp.flow": "Rated discharge: {{250|m3h}}",
    "pump.gtp.head": "Rated total head: {{45|m}}",
    "pump.duty.nohead": "Discharge of each pump shall be {{250|m3h}}.",
    "sub.std": "Submersible pumpsets for borewells shall comply with IS 8034:2018.",
    "sub.duty": "Duty point of each pumpset shall be {{18|m3h}} at {{90|m}} total head.",
    "sub.eff": "Overall pumpset efficiency shall be {{52|pct}} minimum.",
    "sub.motor": "The motors shall be wet type, water filled, complying with IS 9283:2013.",
    "sub.cable": "Flat submersible cables shall be copper conductor, PVC insulated, 3 core {{6|mm2}}, complying with IS 694:2010 and tested to IS 10810.",
    "sub.starter": "An automatic starter with dry run protection and single phasing preventer shall be supplied with every pumpset.",
    "sub.bis": "All pumpsets shall carry the BIS Standard Mark.",
    "tx.std": "Distribution transformers shall comply with IS 1180 (Part 1):2014.",
    "tx.rating": "Transformer rating shall be {{630|kVA}}, 11/0.433 kV, vector group Dyn11.",
    "tx.eel": "Transformers shall comply with energy efficiency level 2 of IS 1180 (Part 1).",
    "tx.cooling": "Transformers shall be outdoor type, copper wound, oil immersed with ONAN cooling.",
    "tx.temprise": "The top oil temperature rise shall be limited to {{35|degC}} above an ambient of {{50|degC}}.",
    "tx.tank": "The tank shall be fabricated from welded mild steel with epoxy paint finish.",
    "tx.routine": "Each transformer shall be subjected to all routine tests as per IS 2026 (Part 1):2011.",
    "tx.typetest": "Bidders shall submit type test reports of the offered design from a NABL accredited laboratory.",
    "tx.rating.big": "Transformer rating shall be {{3150|kVA}}, 33/0.433 kV, vector group Dyn11.",
    "tx.routine.old": "Each transformer shall be subjected to all routine tests as per IS 2026 (Part 1):1977.",
    "tx.routine.omit": "Each transformer shall be subjected to all routine tests prior to despatch.",
    "rcc.exposure": "Exposure condition for the design of the structure shall be taken as severe in terms of IS 456:2000.",
    "rcc.std": "Plain and reinforced cement concrete works shall comply with IS 456:2000.",
    "rcc.grade": "Grade of concrete for all RCC members shall be M30.",
    "rcc.cover": "The nominal cover to reinforcement shall be {{45|mm}}.",
    "rcc.wc": "Maximum free water-cement ratio shall be 0.45.",
    "rcc.cc": "Cement content shall be not less than {{320|kgm3}}.",
    "rcc.cement": "OPC 43 grade cement complying with IS 269:2015 shall be used.",
    "rcc.agg": "Aggregates, both coarse and fine, shall comply with IS 383:2016.",
    "rcc.steel": "Fe 500D TMT reinforcement bars complying with IS 1786:2008 shall be used.",
    "rcc.mix": "Mix proportioning of concrete shall be done as per IS 10262:2019.",
    "rcc.cubes": "Testing of concrete for compressive strength shall be done as per IS 516 (Part 1/Sec 1):2021.",
    "rcc.curing": "Concrete shall be cured for not less than 10 days.",
    "rcc.vibration": "Mechanical needle vibrators shall be used for compaction of concrete.",
    "rcc.mtc": "The contractor shall furnish manufacturer's test certificates for every lot of cement and reinforcement.",
    "rcc.grade.low": "Grade of concrete for all RCC members shall be M20.",
    "rcc.cover.low": "The nominal cover to reinforcement shall be {{30|mm}}.",
    "rcc.wc.high": "Maximum free water-cement ratio shall be 0.55.",
    "rcc.cement.old": "OPC 43 grade cement complying with IS 8112 shall be used.",
    "rcc.steel.old": "Fe 500D TMT reinforcement bars complying with IS 1786:1985 shall be used.",
    "rcc.cubes.old": "Testing of concrete for compressive strength shall be done as per IS 516:1959.",
    "rcc.cubes.omit": "Compressive strength of concrete cubes shall be tested at 7 days and 28 days.",
    "water.std": "The quality of treated water shall comply with IS 10500:2012.",
    "water.ph": "The pH value of treated water shall lie within 6.5 to 8.5.",
    "water.tds": "TDS of treated water shall be limited to {{500|mgl}}.",
    "water.turbidity": "The turbidity of treated water shall be limited to {{1|NTU}}.",
    "water.fluoride": "Fluoride (as F) shall be limited to {{1.0|mgl}}.",
    "water.nitrate": "Nitrate (as NO3) shall be limited to {{45|mgl}}.",
    "water.arsenic": "Arsenic (as As) shall be limited to {{0.01|mgl}}.",
    "water.hardness": "Total hardness (as CaCO3) shall be limited to {{200|mgl}}.",
    "water.ecoli": "No E. coli shall be detected in any 100 ml sample.",
    "water.tests": "Testing of water samples shall be done at a NABL accredited laboratory as per IS 3025 and IS 1622.",
    "water.reports": "The contractor shall submit test reports for every source to the Engineer-in-charge.",
    "water.tds.high": "TDS of treated water shall be limited to {{2000|mgl}}.",
    "water.fluoride.high": "Fluoride (as F) shall be limited to {{1.5|mgl}}.",
    "water.arsenic.high": "Arsenic (as As) shall be limited to {{0.05|mgl}}.",
    "water.turbidity.high": "The turbidity of treated water shall be limited to {{5|NTU}}.",
    "water.tests.no1622": "Testing of water samples shall be done at a NABL accredited laboratory as per IS 3025.",
    "steel.std": "Structural steel plates and sections shall be E250 grade complying with IS 2062:2011.",
    "steel.paint": "Steel work shall be painted with one coat of zinc chromate primer followed by two finishing coats of enamel.",
    "steel.fab": "Steel work shall be fabricated and erected in accordance with approved drawings.",
    "steel.mtc": "The contractor shall submit mill test certificates for all structural steel supplied.",
}

# Companion rewordings used when a plant changes another clause.
DEV2_COMPANIONS: dict[str, str] = {
    "panel.routine": "Each assembly shall undergo routine verification as laid down in IS/IEC 61439-2.",
}
