"""Final compliance report (Markdown).

Every finding carries its evidence and provenance, and every repair its human
decision, so the report explains why each conclusion was reached and who
accepted each change.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import Any, Optional


def _esc(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def report_filename(doc: dict[str, Any]) -> str:
    return f"{re.sub(r'[^\w.-]+', '_', doc['name'])[:80]}-compliance-report.md"


def _prov(p: dict[str, Any], confidence: bool) -> str:
    model = f" ({p['model']})" if p.get("model") else ""
    conf = f" · confidence {p['confidence']}" if confidence else ""
    return f"{p['component']}@{p['componentVersion']} · {p['method']}{model}{conf}"


def build_compliance_report(doc: dict[str, Any], generated_at: Optional[datetime] = None) -> str:
    generated_at = generated_at or datetime.now(timezone.utc)
    findings = doc["findings"]
    count = lambda status: sum(1 for f in findings if f["status"] == status)  # noqa: E731
    lines: list[str] = [
        f"# Compliance review report — {doc['name']}",
        "",
        "> **Decision support, not certification.** Findings and proposed repairs are generated by StandardOS and "
        "must be reviewed by qualified personnel. StandardOS does not certify products or establish legal compliance. "
        "Standards content in the corpus is paraphrased metadata that has not been verified against official BIS "
        "publications.",
        "",
        "## Analysis record",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| Organisation | {_esc(doc['organization'])} |",
        f"| Source format | {doc['type']} |",
        f"| Analysed at | {doc['analyzedAt']} |",
        f"| Report generated | {generated_at.isoformat()} |",
        f"| Pipeline version | {doc.get('pipelineVersion') or '—'} |",
        f"| Standards corpus | {doc.get('corpusVersion') or '—'} ({doc.get('corpusSource') or 'unknown source'}) |",
        f"| Requirements extracted | {doc['requirementCount']} |",
        f"| Standards identified | {doc['standards']} |",
        f"| Readiness | {doc['readiness']}% — `{doc.get('readinessFormula') or 'n/a'}` |",
        "",
    ]
    if doc["warnings"]:
        lines += ["**Parser warnings:**", *[f"- {w}" for w in doc["warnings"]], ""]
    lines += [
        "## Summary",
        "",
        f"- Conflicting: {count('conflicting')}",
        f"- Outdated references: {count('outdated')}",
        f"- Missing / insufficient: {count('missing')}",
        f"- Certification: {count('certification')}",
        f"- Verified: {count('verified')}",
        f"- Findings dismissed by reviewer: {sum(1 for f in findings if f.get('reviewStatus') == 'dismissed')}",
        "",
        "## Findings",
        "",
    ]
    for i, f in enumerate(findings, 1):
        note = f" — “{f['reviewNote']}”" if f.get("reviewNote") else ""
        lines += [
            f"### {i}. {f['title']}",
            "",
            f"**Status:** {f['status']} · **Severity:** {f['severity']} · **Review:** {f.get('reviewStatus') or 'open'}{note}",
            "",
            f"- **Requirement:** {f['requirement']}",
            f"- **Standard:** {f['standard']}",
            f"- **Reason:** {f['reason']}",
            f"- **Recommended action:** {f['action']}",
        ]
        if f.get("evidence"):
            lines.append("- **Evidence:**")
            lines += [f"  - _{e['kind'].replace('_', ' ')}_ — {e['label']}: {e['excerpt']}" for e in f["evidence"]]
        if f.get("provenance"):
            lines.append(f"- **Provenance:** {_prov(f['provenance'], True)}")
        lines.append("")

    lines += ["## Proposed specification repairs", ""]
    if not doc["repairs"]:
        lines += ["No repairs were proposed.", ""]
    for i, r in enumerate(doc["repairs"], 1):
        status = r.get("status") or "pending"
        lines += [f"### Repair {i} — {status}", "", f"- **Original:** {r['original']}", f"- **Proposed:** {r['recommended']}"]
        if status in ("edited", "accepted"):
            lines.append(f"- **Adopted text:** {r.get('finalText') or r['recommended']}")
        lines += [f"- **Evidence:** {r['evidence']}", f"- **Reason:** {r['reason']}"]
        if r.get("provenance"):
            lines.append(f"- **Provenance:** {_prov(r['provenance'], False)}")
        lines.append("")

    lines += [
        "## Requirement mapping",
        "",
        "| # | Requirement | Standard | Clause | Basis | Confidence |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for r in doc["requirements"]:
        conf = f"{r['confidence']:.2f}" if r.get("confidence") is not None else "—"
        lines.append(
            f"| {r['id']} | {_esc(r['text'])} | {_esc(r['standard'])} | {_esc(r['clause'])} | {r.get('basis') or '—'} | {conf} |"
        )
    lines.append("")
    return "\n".join(lines)
